Neos:
  Neos:
    fusion:
      autoInclude:
        DIU.Neos.Content.Slider: true
    userInterface:
      defaultLanguage: de
      translation:
        autoInclude:
          'DIU.Neos.Content.Slider':
            - '**/*'
